import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pierce Hahn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body className={`${inter.className} h-full w-full`}>{children}</body>
    </html>
  );
}
